
#
# Copyright 2004 OpenHosting, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# $Id: dft.py,v 1.2 2005/07/27 21:27:36 grisha Exp $

import os
import pwd
import socket

""" Configuration Defaults

DO NOT EDIT THIS FILE. To change settings, edit your configuration
file. This file is by default /etc/openvps.conf (look below
for CONFIG_FILE for the exact value).

"""

# Configuration directory
CONFIG_DIR = '/etc'

# Configuration file
CONFIG_FILE = os.path.join(CONFIG_DIR, 'openvps-admin.conf')

# Location of the rrd database
VAR_DB_OH = '/var/db/openvps'

# pid
MON_PID_FILE = '/var/run/openvps-recv'

# Whom to send e-mail to
NOTIFY_EMAIL = ['root']

# The From: of the notifications

username = pwd.getpwuid(os.getuid())[0]
hostname = socket.getfqdn()

NOTIFY_FROM = "%s@%s" % (username, hostname) 
